name: test
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
     - run: echo hello world
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout data
        uses: actions/checkout@v4
      - name: install pytest
        run: pip install -U pytest
      - name: test
        run: pytest
