name: test
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
     - run: echo hello world
  test:
    needs: greeting
    runs-on: ubuntu-latest
    strategy:
      matrix:
       py_version: ['3.9','3.10','3.11']
    steps:
      - name: checkout data
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.py_version}}
      - name: install pytest
        run: pip install -U pytest
      - name: test
        run: pytest
  make_file:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout data
        uses: actions/checkout@v4
      - name: run script
        runs: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: test.txt
          path: test.txt
  check_file:
    needs: make_file
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: test.txt
          path: test.txt
      - run: cat test.txt
